CGO45 - Popup Information Bug
Pwnagebird/ConcordiaGO pull request #58
Opened 2020-03-13 18:16 UTC by Pwnagebird

#45

* Added Department and Services to Concordia Constants
* Fixes Buildings without popup information

2020-03-15 16:45 UTC, danielwiktorczyk requested changes
Missing UI

2020-03-16 16:47 UTC, MoreWaqar commented
Has the requested change been handled? Not sure whether to follow through with review at current time

2020-03-16 16:49 UTC, danielwiktorczyk commented
@MoreWaqar we are waiting on the UI component before moving forward with this ticket.

2020-03-18 19:44 UTC, MoreWaqar approved these changes
Approved. Tested the main functionality and everything looks good. Code seems a lot cleaner too.

I think the UI change request is now met and merge can be done.

2020-03-18 19:53 UTC, danielwiktorczyk commented on lib/utilities/application_constants.dart
> +double screenHeight;
Great!

2020-03-18 20:02 UTC, danielwiktorczyk requested changes
Excellent UI addition! 
One small thing: bottom left "More". Can it be made into a similar style as the "Go" bottom right icon, maybe with a '?' info icon? 
![image](https://user-images.githubusercontent.com/24488852/77002335-b806f880-6931-11ea-98bc-e77935ba3965.png)

2020-03-18 23:17 UTC, danielwiktorczyk approved these changes
Bottom left UI uses an icon now rather than a textual label, very good decision! 

This ticket looks ready to go to me 😎

![image](https://user-images.githubusercontent.com/24488852/77016018-db8b6c80-694c-11ea-98f3-2aede49b595f.png)

2020-03-18 23:49 UTC, merged